### ISSUE TITLE
CAD Files?

### ISSUE THREAD

**Issue by 3boysdad** [Yasu3DP/Anycubic-Photon-Mono-Screen-Upgrade#1]
I am actually looking at having the existing aluminum plate milled with the updated dimensions to accommodate the larger screen and fan.  Is there any way you can share with your followers the CAD drawings you used to generate the STLs?

**Comment by matthock** [comment]
Would also be quite interested in this to do some of my own tweaks!

**Comment by 3boysdad** [comment]
@Yasu3DP any thoughts on this?  i can't seem to convert the STL into anything usable in Fusion.

**Comment by Yasu3DP** [comment]
Sorry it took so long (life happened alas) but finally got the cad files done and the parts now are available as .step files which should be good for Fusion, Onshape, FreeCAD et al. Let me know if they are not and I will try my best to stay on top of it.

**Comment by 3boysdad** [comment]
This is awesome. Thank you very much.
